// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PlaylistTracks struct {
	PlaylistID int64 `json:"playlist_id"`
	TrackID    int64 `json:"track_id"`
	Position   int32 `json:"position"`
}

type Playlists struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	IsPublic    bool               `json:"is_public"`
	OwnerID     int64              `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RadioBrowserStations struct {
	ID          int64              `json:"id"`
	Stationuuid string             `json:"stationuuid"`
	Name        string             `json:"name"`
	Url         string             `json:"url"`
	UrlResolved *string            `json:"url_resolved"`
	Homepage    *string            `json:"homepage"`
	Favicon     *string            `json:"favicon"`
	Country     *string            `json:"country"`
	Countrycode *string            `json:"countrycode"`
	State       *string            `json:"state"`
	Language    *string            `json:"language"`
	Codec       *string            `json:"codec"`
	Bitrate     int32              `json:"bitrate"`
	Votes       int32              `json:"votes"`
	Tags        *string            `json:"tags"`
	LastCheckOk bool               `json:"last_check_ok"`
	SyncedAt    pgtype.Timestamptz `json:"synced_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RefreshTokens struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Stations struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	Genre         string             `json:"genre"`
	Description   *string            `json:"description"`
	StreamUrl     string             `json:"stream_url"`
	CoverImageUrl *string            `json:"cover_image_url"`
	IsPublic      bool               `json:"is_public"`
	OwnerID       *int64             `json:"owner_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Streams struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	StationID int64              `json:"station_id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SyncJobs struct {
	RequestID    string             `json:"request_id"`
	Status       string             `json:"status"`
	RequestedBy  string             `json:"requested_by"`
	Scope        []byte             `json:"scope"`
	ErrorMessage *string            `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Tracks struct {
	ID              int64              `json:"id"`
	StationID       int64              `json:"station_id"`
	Title           string             `json:"title"`
	Artist          string             `json:"artist"`
	AudioUrl        string             `json:"audio_url"`
	DurationSeconds int32              `json:"duration_seconds"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Users struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash []byte             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UsersStations struct {
	UserID    int64 `json:"user_id"`
	StationID int64 `json:"station_id"`
}
