// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlist.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const AddTrackToPlaylist = `-- name: AddTrackToPlaylist :exec
INSERT INTO playlist_tracks (playlist_id, track_id, position)
VALUES ($1, $2, $3)
`

type AddTrackToPlaylistParams struct {
	PlaylistID int64 `json:"playlist_id"`
	TrackID    int64 `json:"track_id"`
	Position   int32 `json:"position"`
}

func (q *Queries) AddTrackToPlaylist(ctx context.Context, arg AddTrackToPlaylistParams) error {
	_, err := q.db.Exec(ctx, AddTrackToPlaylist, arg.PlaylistID, arg.TrackID, arg.Position)
	return err
}

const CountPlaylistTracks = `-- name: CountPlaylistTracks :one
SELECT COUNT(*)::bigint FROM playlist_tracks WHERE playlist_id = $1
`

func (q *Queries) CountPlaylistTracks(ctx context.Context, playlistID int64) (int64, error) {
	row := q.db.QueryRow(ctx, CountPlaylistTracks, playlistID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const CountPlaylistsOwnedBy = `-- name: CountPlaylistsOwnedBy :one
SELECT COUNT(*)::bigint FROM playlists WHERE owner_id = $1
`

func (q *Queries) CountPlaylistsOwnedBy(ctx context.Context, ownerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, CountPlaylistsOwnedBy, ownerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const CreatePlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (name, description, is_public, owner_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, is_public, owner_id, created_at, updated_at
`

type CreatePlaylistParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsPublic    bool    `json:"is_public"`
	OwnerID     int64   `json:"owner_id"`
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlists, error) {
	row := q.db.QueryRow(ctx, CreatePlaylist,
		arg.Name,
		arg.Description,
		arg.IsPublic,
		arg.OwnerID,
	)
	var i Playlists
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists WHERE id = $1
`

func (q *Queries) DeletePlaylist(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeletePlaylist, id)
	return err
}

const GetPlaylistByID = `-- name: GetPlaylistByID :one
SELECT id, name, description, is_public, owner_id, created_at, updated_at FROM playlists WHERE id = $1
`

func (q *Queries) GetPlaylistByID(ctx context.Context, id int64) (Playlists, error) {
	row := q.db.QueryRow(ctx, GetPlaylistByID, id)
	var i Playlists
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListPlaylistTrackIDsForUpdate = `-- name: ListPlaylistTrackIDsForUpdate :many
SELECT track_id
FROM playlist_tracks
WHERE playlist_id = $1
ORDER BY track_id ASC
FOR UPDATE
`

func (q *Queries) ListPlaylistTrackIDsForUpdate(ctx context.Context, playlistID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, ListPlaylistTrackIDsForUpdate, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var track_id int64
		if err := rows.Scan(&track_id); err != nil {
			return nil, err
		}
		items = append(items, track_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPlaylistTracks = `-- name: ListPlaylistTracks :many
SELECT t.id, t.station_id, t.title, t.artist, t.audio_url, t.duration_seconds, t.created_at, t.updated_at, pt.position
FROM playlist_tracks pt
JOIN tracks t ON t.id = pt.track_id
WHERE pt.playlist_id = $1
ORDER BY pt.position ASC, pt.track_id ASC
LIMIT $2 OFFSET $3
`

type ListPlaylistTracksParams struct {
	PlaylistID int64 `json:"playlist_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

type ListPlaylistTracksRow struct {
	ID              int64              `json:"id"`
	StationID       int64              `json:"station_id"`
	Title           string             `json:"title"`
	Artist          string             `json:"artist"`
	AudioUrl        string             `json:"audio_url"`
	DurationSeconds int32              `json:"duration_seconds"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Position        int32              `json:"position"`
}

func (q *Queries) ListPlaylistTracks(ctx context.Context, arg ListPlaylistTracksParams) ([]ListPlaylistTracksRow, error) {
	rows, err := q.db.Query(ctx, ListPlaylistTracks, arg.PlaylistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaylistTracksRow
	for rows.Next() {
		var i ListPlaylistTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.StationID,
			&i.Title,
			&i.Artist,
			&i.AudioUrl,
			&i.DurationSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPlaylistsOwnedBy = `-- name: ListPlaylistsOwnedBy :many
SELECT id, name, description, is_public, owner_id, created_at, updated_at
FROM playlists
WHERE owner_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPlaylistsOwnedByParams struct {
	OwnerID int64 `json:"owner_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListPlaylistsOwnedBy(ctx context.Context, arg ListPlaylistsOwnedByParams) ([]Playlists, error) {
	rows, err := q.db.Query(ctx, ListPlaylistsOwnedBy, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlists
	for rows.Next() {
		var i Playlists
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPublicPlaylists = `-- name: ListPublicPlaylists :many
SELECT id, name, description, is_public, owner_id, created_at, updated_at
FROM playlists
WHERE is_public = TRUE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicPlaylistsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublicPlaylists(ctx context.Context, arg ListPublicPlaylistsParams) ([]Playlists, error) {
	rows, err := q.db.Query(ctx, ListPublicPlaylists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlists
	for rows.Next() {
		var i Playlists
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const LockPlaylistForUpdate = `-- name: LockPlaylistForUpdate :one
SELECT id
FROM playlists
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockPlaylistForUpdate(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, LockPlaylistForUpdate, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const MaxPlaylistTrackPosition = `-- name: MaxPlaylistTrackPosition :one
SELECT COALESCE(MAX(position), -1)::int
FROM playlist_tracks
WHERE playlist_id = $1
`

func (q *Queries) MaxPlaylistTrackPosition(ctx context.Context, playlistID int64) (int32, error) {
	row := q.db.QueryRow(ctx, MaxPlaylistTrackPosition, playlistID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const RemoveTrackFromPlaylist = `-- name: RemoveTrackFromPlaylist :one
DELETE FROM playlist_tracks
WHERE playlist_id = $1 AND track_id = $2
RETURNING track_id
`

type RemoveTrackFromPlaylistParams struct {
	PlaylistID int64 `json:"playlist_id"`
	TrackID    int64 `json:"track_id"`
}

func (q *Queries) RemoveTrackFromPlaylist(ctx context.Context, arg RemoveTrackFromPlaylistParams) (int64, error) {
	row := q.db.QueryRow(ctx, RemoveTrackFromPlaylist, arg.PlaylistID, arg.TrackID)
	var track_id int64
	err := row.Scan(&track_id)
	return track_id, err
}

const UpdatePlaylist = `-- name: UpdatePlaylist :one
UPDATE playlists SET
    name = $2,
    description = $3,
    is_public = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, is_public, owner_id, created_at, updated_at
`

type UpdatePlaylistParams struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsPublic    bool    `json:"is_public"`
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlists, error) {
	row := q.db.QueryRow(ctx, UpdatePlaylist,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
	)
	var i Playlists
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdatePlaylistTrackPosition = `-- name: UpdatePlaylistTrackPosition :one
UPDATE playlist_tracks
SET position = $3
WHERE playlist_id = $1 AND track_id = $2
RETURNING track_id
`

type UpdatePlaylistTrackPositionParams struct {
	PlaylistID int64 `json:"playlist_id"`
	TrackID    int64 `json:"track_id"`
	Position   int32 `json:"position"`
}

func (q *Queries) UpdatePlaylistTrackPosition(ctx context.Context, arg UpdatePlaylistTrackPositionParams) (int64, error) {
	row := q.db.QueryRow(ctx, UpdatePlaylistTrackPosition, arg.PlaylistID, arg.TrackID, arg.Position)
	var track_id int64
	err := row.Scan(&track_id)
	return track_id, err
}
