// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlist.sql

package dbsqlc

import (
	"context"
)

const AddTrackToPlaylist = `-- name: AddTrackToPlaylist :exec
INSERT INTO playlist_tracks (playlist_id, track_id, position)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddTrackToPlaylistParams struct {
	PlaylistID int64 `json:"playlist_id"`
	TrackID    int64 `json:"track_id"`
	Position   int32 `json:"position"`
}

func (q *Queries) AddTrackToPlaylist(ctx context.Context, arg AddTrackToPlaylistParams) error {
	_, err := q.db.Exec(ctx, AddTrackToPlaylist, arg.PlaylistID, arg.TrackID, arg.Position)
	return err
}

const CountPlaylistsOwnedBy = `-- name: CountPlaylistsOwnedBy :one
SELECT COUNT(*)::bigint FROM playlists WHERE owner_id = $1
`

func (q *Queries) CountPlaylistsOwnedBy(ctx context.Context, ownerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, CountPlaylistsOwnedBy, ownerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const CreatePlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (name, description, is_public, owner_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, is_public, owner_id, created_at, updated_at
`

type CreatePlaylistParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsPublic    bool    `json:"is_public"`
	OwnerID     int64   `json:"owner_id"`
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlists, error) {
	row := q.db.QueryRow(ctx, CreatePlaylist,
		arg.Name,
		arg.Description,
		arg.IsPublic,
		arg.OwnerID,
	)
	var i Playlists
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists WHERE id = $1
`

func (q *Queries) DeletePlaylist(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeletePlaylist, id)
	return err
}

const GetPlaylistByID = `-- name: GetPlaylistByID :one
SELECT id, name, description, is_public, owner_id, created_at, updated_at FROM playlists WHERE id = $1
`

func (q *Queries) GetPlaylistByID(ctx context.Context, id int64) (Playlists, error) {
	row := q.db.QueryRow(ctx, GetPlaylistByID, id)
	var i Playlists
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListPlaylistTracks = `-- name: ListPlaylistTracks :many
SELECT t.id, t.station_id, t.title, t.artist, t.audio_url, t.duration_seconds, t.created_at, t.updated_at
FROM playlist_tracks pt
JOIN tracks t ON t.id = pt.track_id
WHERE pt.playlist_id = $1
ORDER BY pt.position ASC, pt.track_id ASC
`

func (q *Queries) ListPlaylistTracks(ctx context.Context, playlistID int64) ([]Tracks, error) {
	rows, err := q.db.Query(ctx, ListPlaylistTracks, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tracks
	for rows.Next() {
		var i Tracks
		if err := rows.Scan(
			&i.ID,
			&i.StationID,
			&i.Title,
			&i.Artist,
			&i.AudioUrl,
			&i.DurationSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPlaylistsOwnedBy = `-- name: ListPlaylistsOwnedBy :many
SELECT id, name, description, is_public, owner_id, created_at, updated_at
FROM playlists
WHERE owner_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPlaylistsOwnedByParams struct {
	OwnerID int64 `json:"owner_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListPlaylistsOwnedBy(ctx context.Context, arg ListPlaylistsOwnedByParams) ([]Playlists, error) {
	rows, err := q.db.Query(ctx, ListPlaylistsOwnedBy, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlists
	for rows.Next() {
		var i Playlists
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPublicPlaylists = `-- name: ListPublicPlaylists :many
SELECT id, name, description, is_public, owner_id, created_at, updated_at
FROM playlists
WHERE is_public = TRUE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicPlaylistsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublicPlaylists(ctx context.Context, arg ListPublicPlaylistsParams) ([]Playlists, error) {
	rows, err := q.db.Query(ctx, ListPublicPlaylists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlists
	for rows.Next() {
		var i Playlists
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdatePlaylist = `-- name: UpdatePlaylist :one
UPDATE playlists SET
    name = $2,
    description = $3,
    is_public = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, is_public, owner_id, created_at, updated_at
`

type UpdatePlaylistParams struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsPublic    bool    `json:"is_public"`
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlists, error) {
	row := q.db.QueryRow(ctx, UpdatePlaylist,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
	)
	var i Playlists
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
