// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: radio_browser_station.sql

package dbsqlc

import (
	"context"
)

const CountRadioBrowserStations = `-- name: CountRadioBrowserStations :one
SELECT COUNT(*)::bigint FROM radio_browser_stations
`

func (q *Queries) CountRadioBrowserStations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountRadioBrowserStations)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const UpsertRadioBrowserStation = `-- name: UpsertRadioBrowserStation :exec
INSERT INTO radio_browser_stations (
    stationuuid, name, url, url_resolved, homepage, favicon,
    country, countrycode, state, language, codec,
    bitrate, votes, tags, last_check_ok
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15
)
ON CONFLICT (stationuuid) DO UPDATE SET
    name          = EXCLUDED.name,
    url           = EXCLUDED.url,
    url_resolved  = EXCLUDED.url_resolved,
    homepage      = EXCLUDED.homepage,
    favicon       = EXCLUDED.favicon,
    country       = EXCLUDED.country,
    countrycode   = EXCLUDED.countrycode,
    state         = EXCLUDED.state,
    language      = EXCLUDED.language,
    codec         = EXCLUDED.codec,
    bitrate       = EXCLUDED.bitrate,
    votes         = EXCLUDED.votes,
    tags          = EXCLUDED.tags,
    last_check_ok = EXCLUDED.last_check_ok,
    synced_at     = now(),
    updated_at    = now()
`

type UpsertRadioBrowserStationParams struct {
	Stationuuid string  `json:"stationuuid"`
	Name        string  `json:"name"`
	Url         string  `json:"url"`
	UrlResolved *string `json:"url_resolved"`
	Homepage    *string `json:"homepage"`
	Favicon     *string `json:"favicon"`
	Country     *string `json:"country"`
	Countrycode *string `json:"countrycode"`
	State       *string `json:"state"`
	Language    *string `json:"language"`
	Codec       *string `json:"codec"`
	Bitrate     int32   `json:"bitrate"`
	Votes       int32   `json:"votes"`
	Tags        *string `json:"tags"`
	LastCheckOk bool    `json:"last_check_ok"`
}

func (q *Queries) UpsertRadioBrowserStation(ctx context.Context, arg UpsertRadioBrowserStationParams) error {
	_, err := q.db.Exec(ctx, UpsertRadioBrowserStation,
		arg.Stationuuid,
		arg.Name,
		arg.Url,
		arg.UrlResolved,
		arg.Homepage,
		arg.Favicon,
		arg.Country,
		arg.Countrycode,
		arg.State,
		arg.Language,
		arg.Codec,
		arg.Bitrate,
		arg.Votes,
		arg.Tags,
		arg.LastCheckOk,
	)
	return err
}
