// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: radio_browser_station.sql

package dbsqlc

import (
	"context"
)

const CountRadioBrowserStations = `-- name: CountRadioBrowserStations :one
SELECT COUNT(*)::bigint
FROM radio_browser_stations
WHERE ($1 = '' OR name ILIKE '%' || $1 || '%')
  AND ($2 = '' OR country ILIKE $2)
  AND ($3 = '' OR language ILIKE $3)
`

type CountRadioBrowserStationsParams struct {
	Name     interface{} `json:"name"`
	Country  interface{} `json:"country"`
	Language interface{} `json:"language"`
}

func (q *Queries) CountRadioBrowserStations(ctx context.Context, arg CountRadioBrowserStationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountRadioBrowserStations, arg.Name, arg.Country, arg.Language)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const ListRadioBrowserStations = `-- name: ListRadioBrowserStations :many
SELECT id, stationuuid, name, url, url_resolved, homepage, favicon, country, countrycode, state, language, codec, bitrate, votes, tags, last_check_ok, synced_at, created_at, updated_at
FROM radio_browser_stations
WHERE ($1 = '' OR name ILIKE '%' || $1 || '%')
  AND ($2 = '' OR country ILIKE $2)
  AND ($3 = '' OR language ILIKE $3)
ORDER BY votes DESC, name ASC
LIMIT $5 OFFSET $4
`

type ListRadioBrowserStationsParams struct {
	Name       interface{} `json:"name"`
	Country    interface{} `json:"country"`
	Language   interface{} `json:"language"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) ListRadioBrowserStations(ctx context.Context, arg ListRadioBrowserStationsParams) ([]RadioBrowserStations, error) {
	rows, err := q.db.Query(ctx, ListRadioBrowserStations,
		arg.Name,
		arg.Country,
		arg.Language,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RadioBrowserStations
	for rows.Next() {
		var i RadioBrowserStations
		if err := rows.Scan(
			&i.ID,
			&i.Stationuuid,
			&i.Name,
			&i.Url,
			&i.UrlResolved,
			&i.Homepage,
			&i.Favicon,
			&i.Country,
			&i.Countrycode,
			&i.State,
			&i.Language,
			&i.Codec,
			&i.Bitrate,
			&i.Votes,
			&i.Tags,
			&i.LastCheckOk,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertRadioBrowserStation = `-- name: UpsertRadioBrowserStation :execrows
INSERT INTO radio_browser_stations (
    stationuuid, name, url, url_resolved, homepage, favicon,
    country, countrycode, state, language, codec,
    bitrate, votes, tags, last_check_ok
) SELECT
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15
WHERE NOT EXISTS (
    SELECT 1
    FROM radio_browser_stations
    WHERE url = $3
      AND stationuuid <> $1
)
ON CONFLICT (stationuuid) DO UPDATE SET
    name          = EXCLUDED.name,
    url           = EXCLUDED.url,
    url_resolved  = EXCLUDED.url_resolved,
    homepage      = EXCLUDED.homepage,
    favicon       = EXCLUDED.favicon,
    country       = EXCLUDED.country,
    countrycode   = EXCLUDED.countrycode,
    state         = EXCLUDED.state,
    language      = EXCLUDED.language,
    codec         = EXCLUDED.codec,
    bitrate       = EXCLUDED.bitrate,
    votes         = EXCLUDED.votes,
    tags          = EXCLUDED.tags,
    last_check_ok = EXCLUDED.last_check_ok,
    synced_at     = now(),
    updated_at    = now()
WHERE (
    radio_browser_stations.name,
    radio_browser_stations.url,
    radio_browser_stations.url_resolved,
    radio_browser_stations.homepage,
    radio_browser_stations.favicon,
    radio_browser_stations.country,
    radio_browser_stations.countrycode,
    radio_browser_stations.state,
    radio_browser_stations.language,
    radio_browser_stations.codec,
    radio_browser_stations.bitrate,
    radio_browser_stations.votes,
    radio_browser_stations.tags,
    radio_browser_stations.last_check_ok
) IS DISTINCT FROM (
    EXCLUDED.name,
    EXCLUDED.url,
    EXCLUDED.url_resolved,
    EXCLUDED.homepage,
    EXCLUDED.favicon,
    EXCLUDED.country,
    EXCLUDED.countrycode,
    EXCLUDED.state,
    EXCLUDED.language,
    EXCLUDED.codec,
    EXCLUDED.bitrate,
    EXCLUDED.votes,
    EXCLUDED.tags,
    EXCLUDED.last_check_ok
)
`

type UpsertRadioBrowserStationParams struct {
	Stationuuid string  `json:"stationuuid"`
	Name        string  `json:"name"`
	Url         string  `json:"url"`
	UrlResolved *string `json:"url_resolved"`
	Homepage    *string `json:"homepage"`
	Favicon     *string `json:"favicon"`
	Country     *string `json:"country"`
	Countrycode *string `json:"countrycode"`
	State       *string `json:"state"`
	Language    *string `json:"language"`
	Codec       *string `json:"codec"`
	Bitrate     int32   `json:"bitrate"`
	Votes       int32   `json:"votes"`
	Tags        *string `json:"tags"`
	LastCheckOk bool    `json:"last_check_ok"`
}

func (q *Queries) UpsertRadioBrowserStation(ctx context.Context, arg UpsertRadioBrowserStationParams) (int64, error) {
	result, err := q.db.Exec(ctx, UpsertRadioBrowserStation,
		arg.Stationuuid,
		arg.Name,
		arg.Url,
		arg.UrlResolved,
		arg.Homepage,
		arg.Favicon,
		arg.Country,
		arg.Countrycode,
		arg.State,
		arg.Language,
		arg.Codec,
		arg.Bitrate,
		arg.Votes,
		arg.Tags,
		arg.LastCheckOk,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
