// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: station.sql

package dbsqlc

import (
	"context"
)

const CountStations = `-- name: CountStations :one
SELECT COUNT(*)::bigint FROM stations
`

func (q *Queries) CountStations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountStations)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const CreateStation = `-- name: CreateStation :one
INSERT INTO stations (
    name, genre, description, stream_url, cover_image_url, is_public, owner_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, genre, description, stream_url, cover_image_url, is_public, owner_id, created_at, updated_at
`

type CreateStationParams struct {
	Name          string  `json:"name"`
	Genre         string  `json:"genre"`
	Description   *string `json:"description"`
	StreamUrl     string  `json:"stream_url"`
	CoverImageUrl *string `json:"cover_image_url"`
	IsPublic      bool    `json:"is_public"`
	OwnerID       *int64  `json:"owner_id"`
}

func (q *Queries) CreateStation(ctx context.Context, arg CreateStationParams) (Stations, error) {
	row := q.db.QueryRow(ctx, CreateStation,
		arg.Name,
		arg.Genre,
		arg.Description,
		arg.StreamUrl,
		arg.CoverImageUrl,
		arg.IsPublic,
		arg.OwnerID,
	)
	var i Stations
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Genre,
		&i.Description,
		&i.StreamUrl,
		&i.CoverImageUrl,
		&i.IsPublic,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteStation = `-- name: DeleteStation :exec
DELETE FROM stations WHERE id = $1
`

func (q *Queries) DeleteStation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteStation, id)
	return err
}

const GetStationByID = `-- name: GetStationByID :one
SELECT id, name, genre, description, stream_url, cover_image_url, is_public, owner_id, created_at, updated_at FROM stations WHERE id = $1
`

func (q *Queries) GetStationByID(ctx context.Context, id int64) (Stations, error) {
	row := q.db.QueryRow(ctx, GetStationByID, id)
	var i Stations
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Genre,
		&i.Description,
		&i.StreamUrl,
		&i.CoverImageUrl,
		&i.IsPublic,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListStations = `-- name: ListStations :many
SELECT id, name, genre, description, stream_url, cover_image_url, is_public, owner_id, created_at, updated_at
FROM stations
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListStationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStations(ctx context.Context, arg ListStationsParams) ([]Stations, error) {
	rows, err := q.db.Query(ctx, ListStations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stations
	for rows.Next() {
		var i Stations
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Genre,
			&i.Description,
			&i.StreamUrl,
			&i.CoverImageUrl,
			&i.IsPublic,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateStation = `-- name: UpdateStation :one
UPDATE stations
SET
    name = $2,
    genre = $3,
    description = $4,
    stream_url = $5,
    cover_image_url = $6,
    is_public = $7,
    owner_id = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, name, genre, description, stream_url, cover_image_url, is_public, owner_id, created_at, updated_at
`

type UpdateStationParams struct {
	ID            int64   `json:"id"`
	Name          string  `json:"name"`
	Genre         string  `json:"genre"`
	Description   *string `json:"description"`
	StreamUrl     string  `json:"stream_url"`
	CoverImageUrl *string `json:"cover_image_url"`
	IsPublic      bool    `json:"is_public"`
	OwnerID       *int64  `json:"owner_id"`
}

func (q *Queries) UpdateStation(ctx context.Context, arg UpdateStationParams) (Stations, error) {
	row := q.db.QueryRow(ctx, UpdateStation,
		arg.ID,
		arg.Name,
		arg.Genre,
		arg.Description,
		arg.StreamUrl,
		arg.CoverImageUrl,
		arg.IsPublic,
		arg.OwnerID,
	)
	var i Stations
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Genre,
		&i.Description,
		&i.StreamUrl,
		&i.CoverImageUrl,
		&i.IsPublic,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
