// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stream.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountStreamsByUserID = `-- name: CountStreamsByUserID :one
SELECT COUNT(*)::bigint FROM streams WHERE user_id = $1
`

func (q *Queries) CountStreamsByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, CountStreamsByUserID, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const CreateStream = `-- name: CreateStream :one
INSERT INTO streams (user_id, station_id, started_at, ended_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, station_id, started_at, ended_at, created_at
`

type CreateStreamParams struct {
	UserID    int64              `json:"user_id"`
	StationID int64              `json:"station_id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) CreateStream(ctx context.Context, arg CreateStreamParams) (Streams, error) {
	row := q.db.QueryRow(ctx, CreateStream,
		arg.UserID,
		arg.StationID,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i Streams
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StationID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const EndStreamByID = `-- name: EndStreamByID :one
UPDATE streams
SET ended_at = $2
WHERE id = $1
RETURNING id, user_id, station_id, started_at, ended_at, created_at
`

type EndStreamByIDParams struct {
	ID      int64              `json:"id"`
	EndedAt pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) EndStreamByID(ctx context.Context, arg EndStreamByIDParams) (Streams, error) {
	row := q.db.QueryRow(ctx, EndStreamByID, arg.ID, arg.EndedAt)
	var i Streams
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StationID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetStreamByID = `-- name: GetStreamByID :one
SELECT id, user_id, station_id, started_at, ended_at, created_at FROM streams WHERE id = $1
`

func (q *Queries) GetStreamByID(ctx context.Context, id int64) (Streams, error) {
	row := q.db.QueryRow(ctx, GetStreamByID, id)
	var i Streams
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StationID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const ListStreamsByUserID = `-- name: ListStreamsByUserID :many
SELECT id, user_id, station_id, started_at, ended_at, created_at
FROM streams
WHERE user_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListStreamsByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStreamsByUserID(ctx context.Context, arg ListStreamsByUserIDParams) ([]Streams, error) {
	rows, err := q.db.Query(ctx, ListStreamsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Streams
	for rows.Next() {
		var i Streams
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StationID,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
