// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: syncer.sql

package dbsqlc

import (
	"context"
)

const CreateSyncJob = `-- name: CreateSyncJob :exec
INSERT INTO sync_jobs (request_id, status, requested_by, scope, created_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT DO NOTHING
`

type CreateSyncJobParams struct {
	RequestID   string `json:"request_id"`
	Status      string `json:"status"`
	RequestedBy string `json:"requested_by"`
	Scope       []byte `json:"scope"`
}

func (q *Queries) CreateSyncJob(ctx context.Context, arg CreateSyncJobParams) error {
	_, err := q.db.Exec(ctx, CreateSyncJob,
		arg.RequestID,
		arg.Status,
		arg.RequestedBy,
		arg.Scope,
	)
	return err
}

const GetActiveSyncJob = `-- name: GetActiveSyncJob :one
SELECT request_id, status, requested_by, scope, error_message, started_at, finished_at, created_at
FROM sync_jobs
WHERE status IN ('pending', 'running')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSyncJob(ctx context.Context) (SyncJobs, error) {
	row := q.db.QueryRow(ctx, GetActiveSyncJob)
	var i SyncJobs
	err := row.Scan(
		&i.RequestID,
		&i.Status,
		&i.RequestedBy,
		&i.Scope,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetSyncJobByID = `-- name: GetSyncJobByID :one
SELECT request_id, status, requested_by, scope, error_message, started_at, finished_at, created_at
FROM sync_jobs
WHERE request_id = $1
`

func (q *Queries) GetSyncJobByID(ctx context.Context, requestID string) (SyncJobs, error) {
	row := q.db.QueryRow(ctx, GetSyncJobByID, requestID)
	var i SyncJobs
	err := row.Scan(
		&i.RequestID,
		&i.Status,
		&i.RequestedBy,
		&i.Scope,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const MarkSyncJobCompleted = `-- name: MarkSyncJobCompleted :exec
UPDATE sync_jobs
SET status = 'completed', finished_at = now()
WHERE request_id = $1
`

func (q *Queries) MarkSyncJobCompleted(ctx context.Context, requestID string) error {
	_, err := q.db.Exec(ctx, MarkSyncJobCompleted, requestID)
	return err
}

const MarkSyncJobFailed = `-- name: MarkSyncJobFailed :exec
UPDATE sync_jobs
SET status = 'failed', finished_at = now(), error_message = $2
WHERE request_id = $1
`

type MarkSyncJobFailedParams struct {
	RequestID    string  `json:"request_id"`
	ErrorMessage *string `json:"error_message"`
}

func (q *Queries) MarkSyncJobFailed(ctx context.Context, arg MarkSyncJobFailedParams) error {
	_, err := q.db.Exec(ctx, MarkSyncJobFailed, arg.RequestID, arg.ErrorMessage)
	return err
}

const MarkSyncJobRunning = `-- name: MarkSyncJobRunning :exec
UPDATE sync_jobs
SET status = 'running', started_at = now(), error_message = NULL
WHERE request_id = $1
`

func (q *Queries) MarkSyncJobRunning(ctx context.Context, requestID string) error {
	_, err := q.db.Exec(ctx, MarkSyncJobRunning, requestID)
	return err
}
