// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: track.sql

package dbsqlc

import (
	"context"
)

const CountTracksByStationID = `-- name: CountTracksByStationID :one
SELECT COUNT(*)::bigint FROM tracks WHERE station_id = $1
`

func (q *Queries) CountTracksByStationID(ctx context.Context, stationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, CountTracksByStationID, stationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const CreateTrack = `-- name: CreateTrack :one
INSERT INTO tracks (
    station_id, title, artist, audio_url, duration_seconds
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, station_id, title, artist, audio_url, duration_seconds, created_at, updated_at
`

type CreateTrackParams struct {
	StationID       int64  `json:"station_id"`
	Title           string `json:"title"`
	Artist          string `json:"artist"`
	AudioUrl        string `json:"audio_url"`
	DurationSeconds int32  `json:"duration_seconds"`
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Tracks, error) {
	row := q.db.QueryRow(ctx, CreateTrack,
		arg.StationID,
		arg.Title,
		arg.Artist,
		arg.AudioUrl,
		arg.DurationSeconds,
	)
	var i Tracks
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.Title,
		&i.Artist,
		&i.AudioUrl,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteTrack = `-- name: DeleteTrack :exec
DELETE FROM tracks WHERE id = $1
`

func (q *Queries) DeleteTrack(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteTrack, id)
	return err
}

const GetTrackByID = `-- name: GetTrackByID :one
SELECT id, station_id, title, artist, audio_url, duration_seconds, created_at, updated_at FROM tracks WHERE id = $1
`

func (q *Queries) GetTrackByID(ctx context.Context, id int64) (Tracks, error) {
	row := q.db.QueryRow(ctx, GetTrackByID, id)
	var i Tracks
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.Title,
		&i.Artist,
		&i.AudioUrl,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListTracksByStationID = `-- name: ListTracksByStationID :many
SELECT id, station_id, title, artist, audio_url, duration_seconds, created_at, updated_at
FROM tracks
WHERE station_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTracksByStationIDParams struct {
	StationID int64 `json:"station_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListTracksByStationID(ctx context.Context, arg ListTracksByStationIDParams) ([]Tracks, error) {
	rows, err := q.db.Query(ctx, ListTracksByStationID, arg.StationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tracks
	for rows.Next() {
		var i Tracks
		if err := rows.Scan(
			&i.ID,
			&i.StationID,
			&i.Title,
			&i.Artist,
			&i.AudioUrl,
			&i.DurationSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateTrack = `-- name: UpdateTrack :one
UPDATE tracks SET
    title = $2,
    artist = $3,
    audio_url = $4,
    duration_seconds = $5,
    updated_at = now()
WHERE id = $1 AND station_id = $6
RETURNING id, station_id, title, artist, audio_url, duration_seconds, created_at, updated_at
`

type UpdateTrackParams struct {
	ID              int64  `json:"id"`
	Title           string `json:"title"`
	Artist          string `json:"artist"`
	AudioUrl        string `json:"audio_url"`
	DurationSeconds int32  `json:"duration_seconds"`
	StationID       int64  `json:"station_id"`
}

func (q *Queries) UpdateTrack(ctx context.Context, arg UpdateTrackParams) (Tracks, error) {
	row := q.db.QueryRow(ctx, UpdateTrack,
		arg.ID,
		arg.Title,
		arg.Artist,
		arg.AudioUrl,
		arg.DurationSeconds,
		arg.StationID,
	)
	var i Tracks
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.Title,
		&i.Artist,
		&i.AudioUrl,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
