// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_stations.sql

package dbsqlc

import (
	"context"
)

const CountFollowersByStationID = `-- name: CountFollowersByStationID :one
SELECT COUNT(*)
FROM users_stations
WHERE station_id = $1
`

func (q *Queries) CountFollowersByStationID(ctx context.Context, stationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, CountFollowersByStationID, stationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountStationsByUserID = `-- name: CountStationsByUserID :one
SELECT COUNT(*)
FROM users_stations
WHERE user_id = $1
`

func (q *Queries) CountStationsByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, CountStationsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const FollowStation = `-- name: FollowStation :exec
INSERT INTO users_stations (user_id, station_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowStationParams struct {
	UserID    int64 `json:"user_id"`
	StationID int64 `json:"station_id"`
}

func (q *Queries) FollowStation(ctx context.Context, arg FollowStationParams) error {
	_, err := q.db.Exec(ctx, FollowStation, arg.UserID, arg.StationID)
	return err
}

const GetFollowersByStationID = `-- name: GetFollowersByStationID :many
SELECT u.id, u.email, u.password_hash, u.role, u.created_at, u.updated_at
FROM users u
JOIN users_stations us ON u.id = us.user_id
WHERE us.station_id = $1
ORDER BY u.created_at DESC
`

func (q *Queries) GetFollowersByStationID(ctx context.Context, stationID int64) ([]Users, error) {
	rows, err := q.db.Query(ctx, GetFollowersByStationID, stationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Users
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetStationsByUserID = `-- name: GetStationsByUserID :many
SELECT s.id, s.name, s.genre, s.description, s.stream_url, s.cover_image_url, s.is_public, s.owner_id, s.created_at, s.updated_at
FROM stations s
JOIN users_stations us ON s.id = us.station_id
WHERE us.user_id = $1
ORDER BY s.created_at DESC
LIMIT $2 OFFSET $3
`

type GetStationsByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetStationsByUserID(ctx context.Context, arg GetStationsByUserIDParams) ([]Stations, error) {
	rows, err := q.db.Query(ctx, GetStationsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stations
	for rows.Next() {
		var i Stations
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Genre,
			&i.Description,
			&i.StreamUrl,
			&i.CoverImageUrl,
			&i.IsPublic,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const IsFollowingStation = `-- name: IsFollowingStation :one
SELECT EXISTS(
    SELECT 1
    FROM users_stations
    WHERE user_id = $1 AND station_id = $2
)
`

type IsFollowingStationParams struct {
	UserID    int64 `json:"user_id"`
	StationID int64 `json:"station_id"`
}

func (q *Queries) IsFollowingStation(ctx context.Context, arg IsFollowingStationParams) (bool, error) {
	row := q.db.QueryRow(ctx, IsFollowingStation, arg.UserID, arg.StationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const UnfollowStation = `-- name: UnfollowStation :exec
DELETE FROM users_stations
WHERE user_id = $1 AND station_id = $2
`

type UnfollowStationParams struct {
	UserID    int64 `json:"user_id"`
	StationID int64 `json:"station_id"`
}

func (q *Queries) UnfollowStation(ctx context.Context, arg UnfollowStationParams) error {
	_, err := q.db.Exec(ctx, UnfollowStation, arg.UserID, arg.StationID)
	return err
}
